version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=cinemate
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=arnab
    ports:
      - 5432:5432